version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: dockerfiles/flask.dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    restart: unless-stopped

  streamlit:
    build:
      context: .
      dockerfile: dockerfiles/streamlit.dockerfile
    ports:
      - "8501:8501" 
    environment:
      - STREAMLIT_SERVER_PORT=8501
    volumes:
      - .:/app
    depends_on:
      - web
    restart: unless-stopped
