version: '3.9'

services:
  web:
    build: './flask_app'
    ports:
      - "8080:8080"
    volumes:
      - chatvolume:/app
    restart: unless-stopped

  streamlit:
    build: './streamlit'
    ports:
      - "8501:8501" 
    environment:
      - STREAMLIT_SERVER_PORT=8501
    volumes:
      - chatvolume:/app
    depends_on:
      - web
    restart: unless-stopped

volumes:
  chatvolume: